### ISSUE TITLE
Add better CSS

### ISSUE THREAD

**Issue by joncojonathan** [joncojonathan/mocktranet#2]
Mocktranet is currently ugly, improve its look with some CSS.  A responsive design would be useful, but is not essential.

**Comment by Alabs02** [comment]
@joncojonathan Okay I try and integrate some cool features using materialize css

**Comment by joncojonathan** [comment]
See PR #9 .

**Comment by joncojonathan** [comment]
@Snapster02 I'm still open to further CSS changes if you're interested / have time.  Thanks in advance.

**Comment by emajeru** [comment]
Added some styling changes as well as display for staff directory objects.

**Comment by joncojonathan** [comment]
All complete, thanks.
